---
- name: Installer Apache
  apt:
    name: apache2
    state: present
    update_cache: yes

- name: Déployer la page HTML
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
  notify: Restart Apache
